export const ADD_BIO_INIT = "ADD_BIO_INIT";
export const ADD_BIO_SUCCESS = "ADD_BIO_SUCCESS";
export const ADD_BIO_FAILED = "ADD_BIO_FAILED";

export const GET_BIO_DETAILS_INIT = "GET_BIO_DETAILS_INIT";
export const GET_BIO_DETAILS_SUCCESS = "GET_BIO_DETAILS_SUCCESS";
export const GET_BIO_DETAILS_FAILED = "GET_BIO_DETAILS_FAILED";

export const UPDATE_BIO_INIT = "UPDATE_BIO_INIT";
export const UPDATE_BIO_SUCCESS = "UPDATE_BIO_SUCCESS";
export const UPDATE_BIO_FAILED = "UPDATE_BIO_FAILED";

export const DELETE_BIO_INIT = "DELETE_BIO_INIT";
export const DELETE_BIO_SUCCESS = "DELETE_BIO_SUCCESS";
export const DELETE_BIO_FAILED = "DELETE_BIO_FAILED";

export const OPEN_UPDATE_MODAL_BOX = "OPEN_UPDATE_MODAL_BOX";
export const OPEN_DELETE_MODAL_BOX = "OPEN_DELETE_MODAL_BOX";
export const OPEN_VIEW_MODAL_BOX = "OPEN_VIEW_MODAL_BOX";